addSbtPlugin("org.jetbrains.scala" % "sbt-ide-settings" % "1.1.1")
addSbtPlugin("se.marcuslonnberg" % "sbt-docker" % "1.9.0")
//addSbtPlugin("com.github.sbt" % "sbt-native-packager" % "1.9.4")
//addSbtPlugin("com.heroku" % "sbt-heroku" % "2.1.4")
addSbtPlugin("com.github.sbt" % "sbt-native-packager" % "1.9.4")
